# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-02 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conveyor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conveyor_name', models.CharField(max_length=20)),
                ('read_time', models.DateTimeField()),
                ('read_value', models.IntegerField()),
            ],
            options={
                'ordering': ['read_time'],
            },
        ),
    ]
