# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-02 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conveyor',
            name='read_time',
            field=models.IntegerField(),
        ),
    ]
